### ISSUE TITLE
Close drawer

### ISSUE THREAD

**Issue by fingdo** [yarolegovich/SlidingRootNav#1] opened 2017-03-28 06:38 UTC
the sample click the content layout why can't close drawer.
can I set this?

**Comment by yarolegovich** [comment] 2017-03-28 10:25
Currently there is no out of the box solution. You can manually set onClickListener and do something like: 
```java
if (!nav.isMenuHidden()) {
   nav.closeMenu();
}
```
Will soon update the library with this feature.

**Comment by apascual** [comment] 2017-04-08 01:59
+1

**Comment by gokrish6670** [comment] 2017-04-11 00:18
@apascual  may i know where to add ur code.

**Comment by apascual** [comment] 2017-04-11 08:51
@gokrish6670 place it in the same activity where you are injecting the `SlidingRootNavBuilder`.

The code checks if `rootLinearLayout` consumed the touch event (meaning that something was touched on the menu), and only if **not**, proceed to close it.

**Comment by Fkut** [comment] 2017-04-19 12:26
@apascual but can not be opened the menu by sliding  ((

**Comment by monikarora** [comment] 2017-05-18 06:29
Hey @yarolegovich  i also want to close drawer click into item . please help me

**Comment by AlexLionne** [comment] 2017-06-03 09:46
declare a drawer variable 
`private` SlidingRootNav drawer;

and close the drawer when u switch fragment

`drawer.closeMenu();`

**Comment by zhangchaoxu** [comment] 2017-06-09 02:38
@yarolegovich  looking forward to this new feature.

**Comment by zhangchaoxu** [comment] 2017-06-09 02:50
provide my solution
```
    boolean inDrag;
    View rootDrawerView;

 private void initSlideMenu() {
            mSlideMenu = new SlidingRootNavBuilder(this)
                    .addDragStateListener(new DragStateListener() {
                        @Override
                        public void onDragStart() {
                            inDrag = true;
                        }

                        @Override
                        public void onDragEnd(boolean isMenuOpened) {
                            inDrag = false;
                        }
                    })
                    .withMenuLayout(R.layout.view_drawer)
                    .inject();

            SlidingRootNavLayout layout = mSlideMenu.getLayout();
            rootDrawerView = layout.findViewById(R.id.root_drawer);
    }

    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (!inDrag && mSlideMenu != null && rootDrawerView != null && !mSlideMenu.isMenuHidden()) {
            boolean menuTouched = rootDrawerView.dispatchTouchEvent(ev);
            if (!menuTouched) {
                mSlideMenu.closeMenu();
            }
            return true;
        } else {
            return super.dispatchTouchEvent(ev);
        }
    }
```

**Comment by Aednlaxer** [comment] 2017-06-26 11:03
I prefer to check touch event position and content rectangle.

Activity:
```
override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
	if (hasDrawer() && isTouchEventConsumedByContentMiniature(ev)) {
		return true
	} else {
		return super.dispatchTouchEvent(ev)
	}
}
```

Check if touch event happened inside scaled content area:
```
private fun isTouchEventConsumedByContentMiniature(ev: MotionEvent): Boolean {
	if (!isDrawerOpened() || contentMiniature == null) return false

	if (ev.action == MotionEvent.ACTION_DOWN) {
		val viewLocation = IntArray(2)
		contentMiniature.getLocationOnScreen(viewLocation)
		// Find view bounds rectangle
		val rect = Rect(viewLocation[0], viewLocation[1],
				(viewLocation[0] + contentMiniature.width * SCALE_FACTOR).toInt(),
				(viewLocation[1] + contentMiniature.height * SCALE_FACTOR).toInt())

		// SCALE_FACTOR is a scale value used when initializing a SlideRootNav: .withRootViewScale(SCALE_FACTOR)

		// Check if event is located inside rectangle
		if (rect.contains(ev.x.toInt(), ev.y.toInt())) {
			closeDrawer()
			return true
		}
	}

	return false
}
```

SlidingRootNav injects its layout to view hierarchy. It's necessary to find main content view which may have different IDs and types. View we're looking for is not R.id.drawerContentLayout and is not of HiddenMenuClickConsumer type (also injected by the library). Check Android Studio Layout Inspector for more info on view hierarchy.
```
contentMiniature = (0 until rootNavigation.layout.childCount)
		.map { rootNavigation.layout.getChildAt(it) }
		.firstOrNull { it.id != R.id.drawerContentLayout && it !is HiddenMenuClickConsumer }
```

This may look tricky but works for me.

**Comment by dondeepak** [comment] 2017-06-27 05:04
i am new to android whrn i implement this codes i get lots of error i dont know how to solve. please post full code from SampleActivity

**Comment by Rob--** [comment] 2017-07-08 16:08
Just ensure your activity implements the `OnItemSelectedListener` interface and you can close the menu when an item is selected like this:

```java
SlidingRootNav slidingRootNav;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    slidingRootNav = new SlidingRootNavBuilder(this)
        .withToolbarMenuToggle(toolbar)
        .withMenuOpened(true)
        .withSavedState(savedInstanceState)
        .withMenuLayout(R.layout.drawer)
        .inject();
}

@Override
public void onItemSelected(int position) {
    slidingRootNav.closeMenu(true);
}
```

**Closed** 2017-09-03 07:41 UTC

**Comment by savurajkumar** [comment] 2017-10-09 08:41
How to close menu if we click anywhere other than menu Items,
And 
Now we are closing on Drag Start but I want to close drawer menu outside click

**Comment by dev-JE02** [comment] 2019-03-26 16:07
> I prefer to check touch event position and content rectangle.
> 
> Activity:
> 
> ```kotlin
> override fun dispatchTouchEvent(ev: MotionEvent): Boolean {
> 	if (hasDrawer() && isTouchEventConsumedByContentMiniature(ev)) {
> 		return true
> 	} else {
> 		return super.dispatchTouchEvent(ev)
> 	}
> }
> ```
> 
> Check if touch event happened inside scaled content area:
> 
> ```kotlin
> private fun isTouchEventConsumedByContentMiniature(ev: MotionEvent): Boolean {
> 	if (!isDrawerOpened() || contentMiniature == null) return false
> 
> 	if (ev.action == MotionEvent.ACTION_DOWN) {
> 		val viewLocation = IntArray(2)
> 		contentMiniature.getLocationOnScreen(viewLocation)
> 		// Find view bounds rectangle
> 		val rect = Rect(viewLocation[0], viewLocation[1],
> 				(viewLocation[0] + contentMiniature.width * SCALE_FACTOR).toInt(),
> 				(viewLocation[1] + contentMiniature.height * SCALE_FACTOR).toInt())
> 
> 		// SCALE_FACTOR is a scale value used when initializing a SlideRootNav: .withRootViewScale(SCALE_FACTOR)
> 
> 		// Check if event is located inside rectangle
> 		if (rect.contains(ev.x.toInt(), ev.y.toInt())) {
> 			closeDrawer()
> 			return true
> 		}
> 	}
> 
> 	return false
> }
> ```
> 
> SlidingRootNav injects its layout to view hierarchy. It's necessary to find main content view which may have different IDs and types. View we're looking for is not R.id.drawerContentLayout and is not of HiddenMenuClickConsumer type (also injected by the library). Check Android Studio Layout Inspector for more info on view hierarchy.
> 
> ```kotlin
> contentMiniature = (0 until rootNavigation.layout.childCount)
> 		.map { rootNavigation.layout.getChildAt(it) }
> 		.firstOrNull { it.id != R.id.drawerContentLayout && it !is HiddenMenuClickConsumer }
> ```
> 
> This may look tricky but works for me.

Hey @aednlaxer I can't seem to make your solution work but it is the best I can implement. The problem is the `getLocationOnScreen` method keeps returning 0, so the rectangle always start at the top left of the screen wherein it should be somewhere 1/3 of the screen after the scale has been applied right? Do you have any thoughts about this?

**Comment by aednlaxer** [comment] 2019-04-02 09:42
@dev-JE02 I don't have access to that code anymore so I can't help you with your issue. Is it possible to share more code or create a test project that demonstrates the issue?

**Comment by gatspy** [comment] 2021-10-23 03:32
marked, close drawer.
