### ISSUE TITLE
Not useable with Arabic language

### ISSUE THREAD

**Issue by kulvinder18may** [yarolegovich/SlidingRootNav#25] opened 2017-09-13 13:04 UTC
If i selected Arabic language from my device then drawer open/close not working...otherwise working great. Can you please fix it for that

**Comment by AniketBito** [comment] 2017-12-22 10:43
It works with Arabic language. Just set SlideGravity.RIGHT when language is arabic and SlideGravity.LEFT when English.

.withGravity(SlideGravity.RIGHT)

**Comment by yarolegovich** [comment] 2018-02-03 16:42
A duplicate of #35

**Closed by yarolegovich** 2018-02-03 16:42 UTC
